### ISSUE TITLE
Errors after installing sample plugin

### ISSUE THREAD

**Issue by keirbowden** [forcedotcom/sfdx-plugin-generate#28] opened 2018-06-23 16:00 UTC
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
Execute:

sfdx plugins:generate kbtest2, accept all the defaults
cd kbtest2
sfdx plugins:link

Output: 

Installing dependencies for /Users/kbowden/kbtest2... done
Running prepare script for /Users/kbowden/kbtest2... done

Execute:
sfdx plugins

Output: 

Running prepare script for /Users/kbowden/kbtest2... done
 ▸    Error parsing plugin /Users/kbowden/kbtest2
 ▸    'MODULE_NOT_FOUND': Cannot find module '/Users/kbowden/kbtest2'
 ▸    Error parsing plugin /Users/kbowden/kbtest2
 ▸    'MODULE_NOT_FOUND': Cannot find module '/Users/kbowden/kbtest2'

This output is produced for every sfdx command thereafter. 

Executing sfdx plugins:unlink kbtest2 says that it isn't installed, but the behaviour continues. I have to uninstall sfdx and re-install it to fix.

When executed via bin/run, the plugin behaves as expected, so it seems to be how the plugin is associated with sfdx rather than errors in the plugin itself,

What is the expected behavior?
------------------------------
Linking the example plugin should not cause sfdx to throw errors.

Please mention your Salesforce CLI and OS version.

MacOS version 10.13.5 (17F77
sfdx-cli/6.21.0-9db990b3c9 (darwin-x64) node-v8.9.4

**Comment by amphro** [comment] 2018-06-24 16:20
Thanks for the bug report @keirbowden - it looks like this was caused by the last update when we consumed the latest oclif changes. The manifest file has been renamed to `oclif.manifest.json` instead of `.oclif.manifest.json` which the sfdx CLI doesn't know how to handle yet. I created a PR to fix the Salesforce CLI. https://github.com/heroku/cli-engine/pull/340/files

As a workaround, you can simply rename your manifest file to `.oclif.manifest.json` and all references to it in your `package.json`.

**Comment by keirbowden** [comment] 2018-06-24 17:32
Thanks @amphro - workaround works perfectly!

**Comment by amphro** [comment] 2018-06-28 17:06
Should be fixed in the latest release.

**Closed as completed by amphro** 2018-06-28 17:06 UTC
